# Generated by Django 5.2.1 on 2025-09-16 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_no', models.PositiveIntegerField()),
                ('ward_no', models.PositiveIntegerField()),
                ('property_no', models.CharField(max_length=50)),
                ('partition_no', models.CharField(blank=True, max_length=50, null=True)),
                ('old_ward_no', models.CharField(blank=True, max_length=50, null=True)),
                ('old_property_no', models.CharField(blank=True, max_length=50, null=True)),
                ('property_description', models.CharField(max_length=200)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('flat_shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('building_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title_marathi', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name_marathi', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name_marathi', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_marathi', models.CharField(blank=True, max_length=100, null=True)),
                ('flat_shop_name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('building_name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_marathi', models.TextField(blank=True, null=True)),
                ('residential_toilets', models.PositiveIntegerField(blank=True, null=True)),
                ('commercial_toilets', models.PositiveIntegerField(blank=True, null=True)),
                ('total_toilets', models.PositiveIntegerField(blank=True, null=True)),
                ('water_connection_available', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('number_of_water_connections', models.PositiveIntegerField(blank=True, null=True)),
                ('connection_size', models.CharField(blank=True, max_length=20, null=True)),
                ('rainwater_harvesting', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('solar_system', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remarks_marathi', models.TextField(blank=True, null=True)),
                ('grand_total_carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total_carpet_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total_built_up_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total_built_up_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(choices=[('B', 'B - तळघर / बेसमेंट'), ('G', 'G - तळमजला'), ('M', 'M - पोटमाळा'), ('1', '1 - पहिला मजला'), ('2', '2 - दुसरा मजला'), ('3', '3 - तिसरा मजला'), ('4', '4 - चौथा मजला'), ('5', '5 - पाचवा मजला'), ('6', '6 - सहावा मजला'), ('7', '7 - सातवा मजला'), ('8', '8 - आठवा मजला')], max_length=2)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_construction', models.CharField(choices=[('A', 'A - आर.सी.सी. स्लॅबची घरे / RCC Slab Structures'), ('B', 'B - विटा सिमेंटच्या भिंती /विटा सिमेंटची भारवाहू संरचना'), ('C', 'C - विटा सिमेंटच्या भिंती व टीन कवेलूचे छत'), ('D', 'D - मातीच्या भींती व टिनांचे / कवेलुचे छत'), ('E', 'E - अस्थायी कुळाचे/लाकडी फाट्याचे कड़े बांधकाम'), ('OP-NR', 'OP-NR - खुला भूखंड (प्लॉट)-अनिवासी'), ('OP-R', 'OP-R - खुला भूखंड (प्लॉट)-निवासी')], max_length=10)),
                ('type_of_use', models.CharField(choices=[('R', 'R - निवासी / Residential'), ('C', 'C - वाणिज्य (अनिवासी) / Commercial'), ('NR', 'NR - अनिवासी मालमत्ता / Non-Residential Property'), ('E', 'E - शैक्षणिक / Educational'), ('CC', 'CC - कोचिंग क्लास / Coaching Class'), ('B', 'B - बँक / वित्तीय संस्था / Bank / Financial'), ('O', 'O - कार्यालय / Office'), ('D', 'D - दवाखाना / Clinic'), ('S', 'S - दुकान / Shop'), ('H', 'H - हॉटेल / Hotel'), ('I', 'I - औद्योगिक / Industrial'), ('F', 'F - कारखाना / Factory'), ('M', 'M - मंगल कार्यालय व टॉकीज / Marriage Hall & Cinema'), ('T', 'T - मंदिर / Temple'), ('GYM', 'GYM - व्यायामशाळा / Gym'), ('L', 'L - वाचनालय / Library')], max_length=10)),
                ('type_of_use_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter'), ('Occupier', 'Occupier')], max_length=10)),
                ('length_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carpet_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_carpet_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('built_up_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('built_up_area_sqmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renter_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('renter_full_name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('renter_has_registration', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('renter_calculate_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupier_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('occupier_full_name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('occupier_has_registration', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('occupier_calculate_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_data', to='survey.survey')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
    ]
