# Generated by Django 5.2.1 on 2025-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floordata',
            old_name='occupier_calculate_rent',
            new_name='minus_carpet_area_sqft',
        ),
        migrations.RenameField(
            model_name='floordata',
            old_name='renter_calculate_rent',
            new_name='minus_carpet_area_sqmt',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='construction_year',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='occupier_full_name',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='occupier_full_name_marathi',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='occupier_has_registration',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='renter_full_name',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='renter_full_name_marathi',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='renter_has_registration',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='type_of_construction',
        ),
        migrations.RemoveField(
            model_name='floordata',
            name='type_of_use_desc',
        ),
        migrations.AddField(
            model_name='floordata',
            name='minus_length_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='minus_length_sqmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='minus_width_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='minus_width_sqmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='type_of_use',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('NR', 'Non-Residential'), ('E', 'Educational'), ('B', 'Bank'), ('O', 'Office'), ('D', 'Clinic'), ('S', 'Shop'), ('H', 'Hotel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='grand_total_built_up_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='grand_total_built_up_area_sqmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='grand_total_carpet_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='grand_total_carpet_area_sqmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='plot_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='plot_area_sqmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='property_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='property_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ward_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='zone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
