# Generated by Django 5.2.1 on 2025-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_occupier_calculate_rent_floordata_minus_carpet_area_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floordata',
            name='occupier_calculate_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='occupier_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='occupier_full_name_marathi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='occupier_has_registration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='renter_calculate_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='renter_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='renter_full_name_marathi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='renter_has_registration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('ward_no', 'property_no')},
        ),
    ]
