# Generated by Django 5.2.1 on 2025-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_floordata_occupier_calculate_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floordata',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='type_of_construction',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floordata',
            name='type_of_use_desc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='floor_number',
            field=models.CharField(blank=True, choices=[('B', 'B - तळघर / बेसमेंट'), ('G', 'G - तळमजला'), ('M', 'M - पोटमाळा'), ('1', '1 - पहिला मजला'), ('2', '2 - दुसरा मजला'), ('3', '3 - तिसरा मजला'), ('4', '4 - चौथा मजला'), ('5', '5 - पाचवा मजला'), ('6', '6 - सहावा मजला'), ('7', '7 - सातवा मजला'), ('8', '8 - आठवा मजला')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='occupier_full_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='occupier_full_name_marathi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='occupier_has_registration',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='renter_full_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='renter_full_name_marathi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='type_of_use',
            field=models.CharField(blank=True, choices=[('R', 'Residential'), ('C', 'Commercial'), ('NR', 'Non-Residential'), ('E', 'Educational'), ('B', 'Bank'), ('O', 'Office'), ('D', 'Clinic'), ('S', 'Shop'), ('H', 'Hotel')], null=True),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Renter', 'Renter'), ('Occupier', 'Occupier')], null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name_marathi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name_marathi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='middle_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='middle_name_marathi',
            field=models.CharField(blank=True, null=True),
        ),
    ]
