# Generated by Django 5.2.1 on 2025-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_floordata_construction_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floordata',
            name='measurement_type',
            field=models.CharField(choices=[('inner', 'Inner / अंतर्गत'), ('outer', 'Outer / बाह्य')], default='inner', help_text='Select whether measurements are inner or outer', max_length=10, verbose_name='Measurement Type'),
        ),
        migrations.AlterField(
            model_name='floordata',
            name='type_of_use',
            field=models.CharField(blank=True, choices=[('R', 'Residential'), ('C', 'Commercial'), ('NR', 'Non-Residential'), ('E', 'Educational'), ('B', 'Bank'), ('O', 'Office'), ('D', 'Clinic'), ('S', 'Shop'), ('H', 'Hotel'), ('I', 'Industrial')], null=True),
        ),
    ]
