# Generated by Django 5.2.1 on 2025-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_floordata_measurement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floordata',
            name='measurement_type',
            field=models.CharField(choices=[('inner', 'Inner / अंतर्गत'), ('outer', 'Outer / बाह्य')], help_text='Select whether measurements are inner or outer', max_length=10),
        ),
    ]
