# Generated by Django 5.2.1 on 2025-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floordata',
            name='type_of_use',
            field=models.CharField(blank=True, choices=[('R', 'Residential'), ('C', 'Commercial'), ('NR', 'Non-Residential'), ('E', 'Educational'), ('CC', 'Coaching Class'), ('WEP-PE', 'Veranda Private Educational'), ('B', 'Bank / Financial'), ('O', 'Office'), ('D', 'Clinic'), ('S', 'Shop'), ('H', 'Hotel'), ('I', 'Industrial'), ('F', 'Factory'), ('M', 'Marriage Hall & Cinema'), ('T', 'Temple'), ('DH', 'Dharmashala'), ('VDH', 'Veranda Dharmashala'), ('RP', 'Parking - Residential'), ('TW', 'Mobile Tower'), ('PP', 'Petrol Pump'), ('GYM', 'Gym'), ('L', 'Library'), ('N', 'Not in Use'), ('OP', 'Open Plot'), ('MP', 'Municipal Property')], null=True),
        ),
    ]
