# Generated by Django 5.2.1 on 2025-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_floordata_type_of_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='generated_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF report', null=True, upload_to='generated_reports/'),
        ),
        migrations.AddField(
            model_name='survey',
            name='pdf_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='PDF size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
