# Generated by Django 5.2.1 on 2025-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_survey_generated_pdf_survey_pdf_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='generated_pdf',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='pdf_file_size',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='pdf_generated_at',
        ),
    ]
