# Generated by Django 5.2.1 on 2025-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_survey_generated_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='survey_reports/', verbose_name='Survey PDF Report'),
        ),
    ]
