# Generated by Django 5.2.1 on 2025-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_survey_pdf_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pdf_report_119',
            field=models.FileField(blank=True, null=True, upload_to='survey_reports_119/', verbose_name='Survey PDF Report (119)'),
        ),
    ]
